return {
	{
		"nvim-treesitter/nvim-treesitter",
		lazy = false,
		build = ":TSUpdate",
		config = function()
			configs = require("nvim-treesitter.configs")
			configs.setup({
				ensure_installed = {
					"bash",
					"c",
					"c_sharp",
					"cmake",
					"css",
					"diff",
					"doxygen",
					"fortran",
					"git_config",
					"gitcommit",
					"gitignore",
					"html",
					"htmldjango",
					"http",
					"ini",
					"javascript",
					"jsdoc",
					"json",
					"lua",
					"luadoc",
					"make",
					"markdown",
					"markdown_inline",
					"mermaid",
					"nginx",
					"powershell",
					"python",
					"razor",
					"requirements",
					"rust",
					"sql",
					"toml",
					"tsx",
					"typescript",
					"vim",
					"vimdoc",
					"yaml",
				},
				sync_install = false,
				highlight = { enable = true },
				indent = { enable = true },
			})
		end,
	},
}
